### ISSUE TITLE
It doesn't work well with scaling on windows 10

### ISSUE THREAD

**Issue by wujekbogdan** [skullernet/q2pro#188] opened 2019-07-10 19:01 UTC
I have 4k monitor. I use the native 4k resolution together with 150% scaling. If I set 4k resolution in the game settings then I can only see the part of the image, the missing part is off the screen. So the image looks like it was cropped.  If I disable scaling (set it to 100%) then everything is fine - I can play with 4k resolution.

Windows 10, Nvidia GTX 960

**Comment by skullernet** [comment] 2019-09-14 15:46
Q2PRO version? Windows 10 build?

**Comment by m4son** [comment] 2019-09-20 21:20
>  If I disable scaling (set it to 100%) then everything is fine - I can play with 4k resolution.
Disable scaling for q2pro.exe application.

**Comment by amokmen** [comment] 2019-12-26 09:56
Win10 with 150% scaling: q2pro renders 3840x2160, but it seems like Windows shows only ~1/4 of that resolution (right upper quadrant).

To solve this - in application settings (Right Mouse Click on exe-file), tab "Compatibility", check that application should decides what to do with high resolution.

**Comment by skullernet** [comment] 2020-02-17 17:11
The fact is, since r1531 Q2PRO already includes a .manifest file that should prevent Windows from applying DPI scaling by default. This has worked properly in Windows 10 build 14393 at the time I implemented this, and I've just tested with build 18362 and it still works. No rendering issues here with 4K monitor and DPI scaling set to 200%. So can't reproduce.

**Comment by skullernet** [comment] 2021-09-16 09:39
Closing because this issue has long been fixed. Suggestion to disable scaling in "Compatibility" tab is invalid.

**Closed by skullernet** 2021-09-16 09:39 UTC
