### ISSUE TITLE
CL_ParseServerMessage: Illegible server message

### ISSUE THREAD

**Issue by KOKOSv8** [skullernet/q2pro#305] opened 2023-07-24 12:06 UTC
Hi, im getting this error message on map change on opentdm q2pro server for example this:
PacketFlinger.com ~ OpenTDM ~ Germany #3 -185.17.144.110:27910

Sometimes it does let me load next map without error but most of the time it goes to error and then without server restart its impossible to join.

I use q2berserker client (https://github.com/UCyborg/BerserkerQuake2) and i tried multiple client settings and also diffrent client versions all fail to reconnect.

[q2b_console.log](https://github.com/skullernet/q2pro/files/12145585/q2b_console.log)

Maybe .log file will help a bit dunno, but what i heard its some command from server that client cant understand and thus goes to error.

Please help :/

**Comment by skullernet** [comment] 2023-07-24 21:06
What makes you think this is Q2PRO server problem rather than BerserkerQuake2 client problem? Does the same error happen with 3.20 client?

**Comment by KOKOSv8** [comment] 2023-07-25 07:15
Problem is Berserker have only forum to talk which is impossible to register. So to make sure its 100% client issue thats why im asking here, if there is nothing we can try to change on the server settings wise then the case is closed and I thank you for help.

**Comment by skullernet** [comment] 2023-07-25 09:52
I don't know if this is 100% client issue. I've never run Berserker. That's why I'm asking to test 3.20 client (which would, just as Berserker, use protocol 34 on Q2PRO server). For obvious reasons I can't test all Quake 2 clients out there for compatibility. But if original 3.20 client works and some other client doesn't it would suggest something is wrong with that client.

**Comment by joe0x04** [comment] 2023-07-25 12:27
I run the server in question, and have some extra context that might or might not be useful. All the PF servers are running a fairly recent version of q2proded:

```
joe@main:~$ q2info pf-tdm-de3 version
q2proded r2652~10b99aee Feb 12 2023 Linux x86_64
````

KOKOS reached out to me yesterday to see if there was anything in the server logs, which there isn't. Just a mention of him connecting and then immediately disconnecting. Would setting `developer 1` on a test server show client connection info in the logs? Maybe I'll try that later today.  I'm trying to get the Berserker  client runnging locally to test, but haven't gotten there yet; it's builds but crashes on run, so I'm sure I'm missing something.

Possibly related connection stuff: I have another player who has complained in the past of connection issues (the same Illegible Server Message error), but he's running https://github.com/fruitz-of-dojo/Quake2 on an ancient 32bit macbook for a client. I've tried testing, but I only have an m1 macbook and it flat-out refuses to run. So I can't test this. He gets the same error message on connect *intermittently*, sometimes it works fine, others no dice. He said the fruitz-of-dojo version is just a straight up mac port of 3.21. I dunno. He has told me this has never been a problem on any server running r1q2, but let's be real, any version of r1q2 running in the wild is almost certainly ancient at this point too. I'm looking into upgrading all Tastyspleen servers to q2pro (currently r1q2) but I wanted to get a handle on these little issues first. 

I have also noticed connection issues with the Tastyspleen bot Wallfly, it has a hard time connecting to q2pro servers.  It's an old build of 3.21 as well it can take minutes sometimes for it to reconnect after a map change. And sometimes it just never comes back. Sometimes killing the process and restarting will bring it back. The bot runs at a VERY low rate and fps and that seems to cause slow connections too (I just tried with q2pro client and it acts the same).

```
joe@main:~$ q2rcon pf-tourney status
Current map: q2dm1

num score ping name            lastmsg address              rate pr fps
--- ----- ---- --------------- ------- --------------------- ----- -- ---
  0     0 PRIM WallFly[BZZZ]       178 23.2xx.170.xxx:40362    100 34   0 
  1     0      40 claire                        21 98.1x.x8.2xx:38647        100 36   30 

No TCP clients.

```
This was just now, notice wallfly is not spawned yet. I connected with rate 100 and fps 5 (although it's using 30) and it took around 20 seconds to actually connect and get spawned. I tried with both protocol 36 and 34 with the same result. Maybe this is intended behavior, not sure. This behavior is not present when connecting to (TS's) r1q2 servers.

I'm still working on testing stuff to get a repeatable set of circumstances. 

Thanks for all your hard work Skuller, q2pro is a fantastic program and well appreciate your work on it!

**Comment by KOKOSv8** [comment] 2023-07-25 12:52
> I don't know if this is 100% client issue. I've never run Berserker. That's why I'm asking to test 3.20 client (which would, just as Berserker, use protocol 34 on Q2PRO server). For obvious reasons I can't test all Quake 2 clients out there for compatibility. But if original 3.20 client works and some other client doesn't it would suggest something is wrong with that client.

ok, i just tested quake2 3.20 on the server where berserker have parse message error and yes this client also gets this error staright away. I have also checked other q2pro server where i could connect, then I voted to change to q2dm3 and it went the same error again.

**Comment by skullernet** [comment] 2023-07-25 18:46
> ok, i just tested quake2 3.20 on the server where berserker have parse message error and yes this client also gets this error staright away.

Thanks for testing! I think I know what this issue is. It's an old Quake 2 bug whereas any literal 0xff bytes in a string would be read as -1 on the client, which would mess up message parsing because -1 also acts as EOF marker. Apparently Yamagi fixes this but the bug is still present in Berserker and original 3.20 client of course.

What's actually happening is a combination of two bugs: original bug in client message parsing code, and a bug in OpenTDM version that PacketFlinger.com servers use which triggers it by including random uninitialized bytes from stack at the end of global CS_STATUSBAR configstring. See here:

```
02a0 : 66 20 32 38 20 78 6c 20 31 30 20 79 62 20 2d 31 : f 28 xl 10 yb -1
02b0 : 00 0d 0e 00 38 30 20 73 74 61 74 5f 73 74 72 69 : ....80 stat_stri
02c0 : 6e 67 20 32 38 20 65 6e 64 69 66 20 ff 03 00 0d : ng 28 endif ....
02d0 : 1d 00 30 00 0d 1e 00 32 35 00 0d 1f 00 38 30 37 : ..0....25....807
```

`ff 03` bytes are just junk. So this issue is definitely not Q2PRO server issue.

**Comment by skullernet** [comment] 2023-07-25 19:44
> I have also noticed connection issues with the Tastyspleen bot Wallfly, it has a hard time connecting to q2pro servers.

> The bot runs at a VERY low rate and fps and that seems to cause slow connections too (I just tried with q2pro client and it acts the same).

Well, if you use rate as low as 100 this is expected. On connection to 185.17.144.110:27910 protocol 34 client receives around 7400 bytes as part of initial connection process. If the rate is capped at 100 bytes/sec it would take 74 seconds to transmit these. I think R1Q2 server just doesn't respect rate cap during connection, whereas Q2PRO server does.

**Comment by joe0x04** [comment] 2023-07-25 20:30
> What's actually happening is a combination of two bugs: original bug in client message parsing code, and a bug in OpenTDM version that PacketFlinger.com servers use which triggers it by including random uninitialized bytes from stack at the end of global CS_STATUSBAR configstring.

lol oops. I'll go through all that statusbar code, it's probably related to the weapon hud that was added a couple years ago. Thanks!

**Comment by joe0x04** [comment] 2023-07-25 20:30
> Well, if you use rate as low as 100 this is expected. On connection to 185.17.144.110:27910 protocol 34 client receives around 7400 bytes as part of initial connection process. If the rate is capped at 100 bytes/sec it would take 74 seconds to transmit these. I think R1Q2 server just doesn't respect rate cap during connection, whereas Q2PRO server does.

This makes perfect sense

**Comment by RailWolf** [comment] 2023-07-27 17:28
Is there any way to fix this so a client can have a lower rate without issue like how it works on r1q2 and the other server binaries? The illegible server message and prolonged connection times are issues specific to q2pro and it has an impact on WallFly[BZZZ].

I've looked into this issue a good bit. I made a hacky patch to the WallFly[BZZZ] source so it at least stops crashing on the illegible server message, but there's still issues with prolonged connection times. 

Basically what I'm seeing is on connection after the initial exchange the client is sending data but the server doesn't send any replies for a long time. After a few tries of the client sending small packets the sever finally responds and then it connects. Kinda as if the client is going "Hello?..... Hello?..... Hello?....." then the server decides to finally answer after a while. I have seen inconsistencies in this behavior as well. Currently at work but I can pull up my old notes and packet captures if you're interested in deeper details.

**Comment by skullernet** [comment] 2023-07-27 18:35
> Is there any way to fix this so a client can have a lower rate without issue like how it works on r1q2 and the other server binaries?

I don't see an issue worth fixing here. Just don't set such ridiculously low rate? Q2PRO server is doing what it is instructed to. Alternatively, minimum allowed client rate can be capped by `sv_min_rate` cvar on the server. By default it is 100, but can be set to e.g. 5000 to avoid stalling misconfigured clients.

Can you confirm if setting rate to 5000 fixes WallFly[BZZZ] connection issues?

> The illegible server message and prolonged connection times are issues specific to q2pro and it has an impact on WallFly[BZZZ].

As I explained, illegible server message issue described in this bug report is an OpenTDM bug and has nothing to do with Q2PRO. Unless you are referencing some different issue.

**Comment by RailWolf** [comment] 2023-07-27 18:38
To add to this, and I don't know if it's specifically related, but I have seen reports of networking issues with the latest versions of q2pro client. In the TDM scene it's recommended to use r1910 since it does not have the lag issues that have been reported. I believe there is an issue somewhere that needs to be looked at. I personally have not had time to dig into it in the q2pro code to see what's wrong, so I can't recommend a place to look.

**Comment by skullernet** [comment] 2023-07-28 04:06
>I have seen reports of networking issues with the latest versions of q2pro client. In the TDM scene it's recommended to use r1910 since it does not have the lag issues that have been reported.

I have not heard of such issues. If this is indeed the case, it would be helpful to know which revision since r1910 introduced these lag issues. But it should really be in a separate bug report.

**Comment by skullernet** [comment] 2023-07-28 04:12
Closing this because original issue reported here has been analyzed and found to be not Q2PRO related. If connection problems persist (after increasing rate to a more sensible value), feel free to open another bug report.

**Closed by skullernet** 2023-07-28 04:12 UTC
