### ISSUE TITLE
Broken HUD and Models

### ISSUE THREAD

**Issue by BlackStalker502** [skullernet/q2pro#196] opened 2020-04-19 16:53 UTC
1. When game is launching - nothing happens (black screen) and required restart the game in windowed mode.
2. When gameplay is starting - appear artifacts: in certain angles HUD is disappearing, pause menu is distorted. And for fix it need to edit any interface related settings.
3. Like with HUD - viewmodel in certain angles is disappear, also except viewmodels, blaster bullets and machinegun impacts are drawn closest enemy and props models (and it looks enough creepy for me...). Enemies, props and items are invisible, in MP viewmodel are drawn on respawn points and etc...

I using default Q2 .pak's from Steam Version and 32-bit Q2PRO client. And i can send video with these bugs, if required

P.s Sorry for my english)))

**Comment by skullernet** [comment] 2022-12-05 23:40
Probably duplicate of #190.

**Closed by skullernet** 2022-12-05 23:40 UTC
